<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MaterialPurchaseRegistersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('material_purchase_registers')->delete();
        
        \DB::table('material_purchase_registers')->insert(array (
            0 => 
            array (
                'id' => 1,
                'product_id' => 3,
                'entry_date' => '2026-02-25',
                'opening_qty' => '0',
                'opening_value' => '0.00',
                'challan_or_bill_no' => 'c-8849332',
                'challan_date' => '2026-02-20',
                'supplier_name' => 'Tatiana Clark',
                'supplier_address' => 'Aftabnagar, Dhaka',
                'supplier_registration_no' => '66758488839',
                'product_name' => 'Food Color',
                'purchase_qty' => '1500.00',
                'unit' => 'kg',
                'purchase_value' => '150000.00',
                'supplementary_duty' => NULL,
                'vat_amount' => '11250.00',
                'total_qty' => '1500.00',
                'total_value' => '150000.00',
                'used_qty' => '5.00',
                'used_value' => '500.00',
                'closing_qty' => '1495.00',
                'closing_value' => '149500.00',
                'remark' => NULL,
                'created_at' => '2026-02-26 08:19:19',
                'updated_at' => '2026-02-26 08:19:19',
            ),
            1 => 
            array (
                'id' => 2,
                'product_id' => 3,
                'entry_date' => '2026-02-26',
                'opening_qty' => '1495.00',
                'opening_value' => '149500.00',
                'challan_or_bill_no' => 'c-8849335',
                'challan_date' => '2026-02-23',
                'supplier_name' => 'Venus Alvarado',
                'supplier_address' => 'China',
                'supplier_registration_no' => '66758488870',
                'product_name' => 'Food Color',
                'purchase_qty' => '15.00',
                'unit' => 'kg',
                'purchase_value' => '1500.00',
                'supplementary_duty' => NULL,
                'vat_amount' => '75.00',
                'total_qty' => '1510.00',
                'total_value' => '151000.00',
                'used_qty' => '10.00',
                'used_value' => '1000.00',
                'closing_qty' => '1500.00',
                'closing_value' => '150000.00',
                'remark' => NULL,
                'created_at' => '2026-02-26 11:43:30',
                'updated_at' => '2026-02-26 11:43:30',
            ),
            2 => 
            array (
                'id' => 3,
                'product_id' => 8,
                'entry_date' => '2026-02-26',
                'opening_qty' => '0',
                'opening_value' => '0.00',
                'challan_or_bill_no' => 'c-8849345',
                'challan_date' => '2026-02-23',
                'supplier_name' => 'Rasel Mia Khalifa',
                'supplier_address' => 'Canada',
                'supplier_registration_no' => '66758488875',
                'product_name' => 'Rice',
                'purchase_qty' => '1000.00',
                'unit' => 'Kg',
                'purchase_value' => '26000.00',
                'supplementary_duty' => NULL,
                'vat_amount' => '1300.00',
                'total_qty' => '1000.00',
                'total_value' => '26000.00',
                'used_qty' => NULL,
                'used_value' => NULL,
                'closing_qty' => '1000.00',
                'closing_value' => '26000.00',
                'remark' => NULL,
                'created_at' => '2026-02-26 17:07:21',
                'updated_at' => '2026-02-26 17:07:21',
            ),
            3 => 
            array (
                'id' => 4,
                'product_id' => 8,
                'entry_date' => '2026-02-26',
                'opening_qty' => '1000.00',
                'opening_value' => '26000.00',
                'challan_or_bill_no' => 'c-8849398',
                'challan_date' => '2026-02-25',
                'supplier_name' => 'Liton Das',
                'supplier_address' => 'China',
                'supplier_registration_no' => '66758488889',
                'product_name' => 'Rice',
                'purchase_qty' => '100.00',
                'unit' => 'Kg',
                'purchase_value' => '2600.00',
                'supplementary_duty' => NULL,
                'vat_amount' => '0.00',
                'total_qty' => '1100.00',
                'total_value' => '28600.00',
                'used_qty' => NULL,
                'used_value' => NULL,
                'closing_qty' => '1100.00',
                'closing_value' => '28600.00',
                'remark' => NULL,
                'created_at' => '2026-02-26 17:19:40',
                'updated_at' => '2026-02-26 17:19:40',
            ),
            4 => 
            array (
                'id' => 5,
                'product_id' => 8,
                'entry_date' => '2026-02-26',
                'opening_qty' => '1100.00',
                'opening_value' => '28600.00',
                'challan_or_bill_no' => 'c-88775847',
                'challan_date' => '2026-02-25',
                'supplier_name' => 'Tushar Bro',
                'supplier_address' => 'China',
                'supplier_registration_no' => '66758489077',
                'product_name' => 'Rice',
                'purchase_qty' => '200.00',
                'unit' => 'Kg',
                'purchase_value' => '5600.00',
                'supplementary_duty' => NULL,
                'vat_amount' => '280.00',
                'total_qty' => '1300.00',
                'total_value' => '34200.00',
                'used_qty' => '0.00',
                'used_value' => '0.00',
                'closing_qty' => '1300.00',
                'closing_value' => '34200.00',
                'remark' => NULL,
                'created_at' => '2026-02-26 17:24:25',
                'updated_at' => '2026-02-26 17:24:25',
            ),
            5 => 
            array (
                'id' => 6,
                'product_id' => 4,
                'entry_date' => '2026-03-11',
                'opening_qty' => '0',
                'opening_value' => '0.00',
                'challan_or_bill_no' => 'B-897746',
                'challan_date' => '2026-03-07',
                'supplier_name' => 'Rasel Ahmed',
                'supplier_address' => 'Motijheel',
                'supplier_registration_no' => NULL,
                'product_name' => 'Plastic',
                'purchase_qty' => '500.00',
                'unit' => 'kg',
                'purchase_value' => '50000.00',
                'supplementary_duty' => '0.00',
                'vat_amount' => '0.00',
                'total_qty' => '500.00',
                'total_value' => '50000.00',
                'used_qty' => '0.00',
                'used_value' => '0.00',
                'closing_qty' => '500.00',
                'closing_value' => '50000.00',
                'remark' => NULL,
                'created_at' => '2026-03-11 15:53:52',
                'updated_at' => '2026-03-11 15:53:52',
            ),
            6 => 
            array (
                'id' => 7,
                'product_id' => 4,
                'entry_date' => '2026-03-11',
                'opening_qty' => '500.00',
                'opening_value' => '50000.00',
                'challan_or_bill_no' => 'B-7764998',
                'challan_date' => '2026-03-07',
                'supplier_name' => 'Hasnain Sadid',
                'supplier_address' => 'Aftabnagar',
                'supplier_registration_no' => NULL,
                'product_name' => 'Plastic',
                'purchase_qty' => '200.00',
                'unit' => 'kg',
                'purchase_value' => '20000.00',
                'supplementary_duty' => '600.00',
                'vat_amount' => '0.00',
                'total_qty' => '700.00',
                'total_value' => '70000.00',
                'used_qty' => '0.00',
                'used_value' => '0.00',
                'closing_qty' => '700.00',
                'closing_value' => '70000.00',
                'remark' => NULL,
                'created_at' => '2026-03-11 15:57:26',
                'updated_at' => '2026-03-11 15:57:26',
            ),
        ));
        
        
    }
}